title: Hoa Le's Personal Website
description: Hoa Le's personal portfolio and blog
baseurl: "" # Leave empty for GitHub Pages root
url: "https://hoale2908.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-tagging

collections:
  posts:
    output: true

