title: Hoa Le (Harvey)
logo: /assets/img/image.png
description: 
FRM Part 2 Candidate | CFA Level II Candidate 
<br><br>
MSF, MBA
<br><br>
<a href="https://www.linkedin.com/in/lehoa2908">View My LinkedIn Profile</a> 



