# title: Harvey Le
logo: /assets/img/image.png
description: 
  Harvey Le's personal website
remote_theme: pages-themes/minimal@v0.2.0
header_pages:
  - about.md
  - portfolio.md
# theme: minima
plugins:
- jekyll-remote-theme

