title: Hoa Le (Harvey)
logo: /assets/img/image.png
description: FRM Part 2 Exam Candidate <br> Passed CFA Level I <br> MBA, MSF
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme