title: Harvey Le's Personal Website
description: Harvey Le's personal blog and portfolio
baseurl: "" # Leave empty for GitHub Pages root
url: "https://hoale2908.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate